// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI6rU3Mfnvn-e2HxyQur2KFf6CvKNRXk4',
    appId: '1:140061586960:web:65f0053d30808003537c95',
    messagingSenderId: '140061586960',
    projectId: 'chatai-69eab',
    authDomain: 'chatai-69eab.firebaseapp.com',
    storageBucket: 'chatai-69eab.firebasestorage.app',
    measurementId: 'G-L39YHGW5DX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8kCAdYwSfpJbvu0VhQ6kuK3wJ2t5Z0XA',
    appId: '1:140061586960:android:bf405c5d7d9a68d8537c95',
    messagingSenderId: '140061586960',
    projectId: 'chatai-69eab',
    storageBucket: 'chatai-69eab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZxafP8masKS6cu2j5bjIwIcWORsN4Zo0',
    appId: '1:140061586960:ios:c1503b9a16336688537c95',
    messagingSenderId: '140061586960',
    projectId: 'chatai-69eab',
    storageBucket: 'chatai-69eab.firebasestorage.app',
    iosClientId: '140061586960-5n1ifsd6l87assfeldfsr69mtv2bv4va.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZxafP8masKS6cu2j5bjIwIcWORsN4Zo0',
    appId: '1:140061586960:ios:c1503b9a16336688537c95',
    messagingSenderId: '140061586960',
    projectId: 'chatai-69eab',
    storageBucket: 'chatai-69eab.firebasestorage.app',
    iosClientId: '140061586960-5n1ifsd6l87assfeldfsr69mtv2bv4va.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI6rU3Mfnvn-e2HxyQur2KFf6CvKNRXk4',
    appId: '1:140061586960:web:f5f424568d0db8fd537c95',
    messagingSenderId: '140061586960',
    projectId: 'chatai-69eab',
    authDomain: 'chatai-69eab.firebaseapp.com',
    storageBucket: 'chatai-69eab.firebasestorage.app',
    measurementId: 'G-4EC5SP5560',
  );

}